name: SPECData-linux
channels:
- defaults
dependencies:
- cairo=1.14.8=0
- cffi=1.9.1=py27_0
- cryptography=1.7.1=py27_0
- cycler=0.10.0=py27_0
- enum34=1.1.6=py27_0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- glib=2.50.2=1
- harfbuzz=0.9.39=2
- idna=2.2=py27_0
- ipaddress=1.0.18=py27_0
- libffi=3.2.1=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libxml2=2.9.4=0
- matplotlib=1.5.1=np111py27_0
- mkl=2017.0.1=0
- numpy=1.11.3=py27_0
- openssl=1.0.2k=1
- pango=1.40.3=1
- pcre=8.39=1
- pip=9.0.1=py27_1
- pixman=0.34.0=0
- pyasn1=0.2.3=py27_0
- pycairo=1.10.0=py27_0
- pycparser=2.17=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=4.11.4=py27_4
- python=2.7.13=0
- python-dateutil=2.6.0=py27_0
- pytz=2017.2=py27_0
- qt=4.8.7=4
- readline=6.2=2
- setuptools=27.2.0=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - asn1crypto==0.22.0
  - astropy==1.3.2
  - astroquery==0.3.5
  - beautifulsoup4==4.6.0
  - html5lib==0.999999999
  - keyring==10.3.2
  - packaging==16.8
  - periodic==2.1.1
  - pyqtgraph==0.10.0
  - pysqlite==2.8.3
  - requests==2.14.2
  - secretstorage==2.3.1
  - sqlalchemy==0.7.7
  - webencodings==0.5.1

