name: SPECData-osx
channels:
- defaults
dependencies:
- cffi=1.9.1=py27_0
- cryptography=1.7.1=py27_0
- enum34=1.1.6=py27_0
- freetype=2.5.5=2
- idna=2.2=py27_0
- ipaddress=1.0.18=py27_0
- libpng=1.6.27=0
- mkl=2017.0.1=0
- numpy=1.12.0=py27_0
- openssl=1.0.2k=1
- pip=9.0.1=py27_1
- pyasn1=0.2.3=py27_0
- pycparser=2.17=py27_0
- pyqt=4.11.4=py27_4
- pyqtgraph=0.9.10=py27_1
- python=2.7.13=0
- qt=4.8.7=4
- qtpy=1.2.1=py27_0
- readline=6.2=2
- setuptools=27.2.0=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - appdirs==1.4.3
  - astropy==1.3.2
  - astroquery==0.3.5
  - beautifulsoup4==4.5.3
  - configparser==3.5.0
  - cycler==0.10.0
  - entrypoints==0.2.2
  - enum==0.4.6
  - functools32==3.2.3.post2
  - html5lib==0.999999999
  - keyring==10.3.2
  - matplotlib==2.0.0
  - nbconvert==4.2.0
  - packaging==16.8
  - periodic==2.1.1
  - pygments==2.1.3
  - pyparsing==2.2.0
  - pysqlite==2.8.3
  - python-contrib-nbextensions==alpha
  - python-dateutil==2.6.0
  - pytz==2017.2
  - requests==2.13.0
  - scipy==0.19.0
  - sqlalchemy==0.7.7
  - subprocess32==3.2.7
  - webencodings==0.5.1

